name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Sanity checks
        run: |
          python -m compileall .
          python -m pip check
          python -c "import fastapi, uvicorn; print('imports OK')"
      - name: Alembic upgrade (SQLite)
        env:
          DATABASE_URL: sqlite:///./ci.db
        run: |
          alembic upgrade head
